<?php
//sending mail

    if ( ! function_exists( 'wp_handle_upload' ) ) {
        require_once( ABSPATH . 'wp-admin/includes/file.php' );
    }
    
    $uploadedfile = $_FILES['file'];
    
    $upload_overrides = array( 'test_form' => false );
    
    $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
    
    if ( $movefile && ! isset( $movefile['error'] ) ) {
        echo "File is valid, and was successfully uploaded.\n";
        var_dump( $movefile );
    } else {
        /**
         * Error generated by _wp_handle_upload()
         * @see _wp_handle_upload() in wp-admin/includes/file.php
         */
        echo $movefile['error'];
    }

?>
<form name="frm" method="post" enctype="multipart/form-data">
<p><h3>Register your GARMIN products to be eligible for benefits.</h3></p>
<label for="serail-product">Please specify your product's serial number:</label>
<input type="file" name="uploaded_file" id="image" accept="image/gif, image/jpeg, image/png" />
<input type="submit" value="Submit" name="send-serial" id="send-serial">
</form>
<?php
